version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: titogo_admin
      POSTGRES_PASSWORD: Protonsysdba1986
      POSTGRES_DB: flow
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
